version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: ./services/php/${DOCKER_PHP_VERSION}/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_php
    container_name: ${DOCKER_PROJECT_NAME}_php
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    ports:
    - '9000:9000'
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
      - ./services/php/${DOCKER_PHP_VERSION}/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./services/php/${DOCKER_PHP_VERSION}/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./services/php/${DOCKER_PHP_VERSION}/conf.d/supervisord.ini:/etc/supervisor.d/supervisord.ini
      - ./scripts/php.sh:/scripts/php.sh
    environment:
      - PROJECT_PATCH=${DOCKER_PROJECT_PATCH}
      - MYSQL_HOST=${DOCKER_PROJECT_NAME}_mysql
      - PHP_IDE_CONFIG=serverName=${DOCKER_PROJECT_DOMAIN}
    command: /scripts/php.sh

  nginx:
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
    image: ${DOCKER_PROJECT_NAME}_nginx
    container_name: ${DOCKER_PROJECT_NAME}_nginx
    working_dir: ${DOCKER_PROJECT_PATCH}
    networks:
      - net
    ports:
      - '${DOCKER_NGINX_PORT:-80}:80'
    volumes:
      - ${DOCKER_PROJECT_ROOT}:${DOCKER_PROJECT_PATCH}
      - ./services/nginx/conf.d/${DOCKER_NGINX_CONFIG}:/etc/nginx/conf.d/docker.conf.template
      - ./scripts/nginx.sh:/scripts/nginx.sh
    environment:
      - PROJECT_PATCH=${DOCKER_PROJECT_PATCH}
      - SERVER_NAME=${DOCKER_PROJECT_DOMAIN}
      - ROOT=${DOCKER_NGINX_ROOT}
      - CONFIG=${DOCKER_NGINX_CONFIG}
      - PHP_HOST=${DOCKER_PROJECT_NAME}_php
      - VIRTUAL_HOST=${DOCKER_PROJECT_DOMAIN}
    command: /scripts/nginx.sh
    depends_on:
      - php

networks:
  net:
    driver: bridge
