---
name: static analysis
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPStan
        uses: docker://jakzal/phpqa:php8.0-alpine
        with:
          args: phpstan analyze app/ -l 1
      - name: PHP-CS
        uses: docker://jakzal/phpqa:php8.0-alpine
        with:
          args: phpcs -s --extensions=php --standard=PSR12 --report=junit -n app/
...